### ISSUE TITLE
provider crashed - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rayalan** [buildkite/terraform-provider-buildkite#448] opened 2023-12-05 14:19 UTC
**Describe the bug**

After defining a default queue for a cluster in v1.0.6, the provider segfaults in both v1.0.6 and v1.1.1 in Terraform when making a plan. The stack trace is: 

```
Stack trace from the terraform-provider-buildkite_v1.1.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b7509]

goroutine 411 [running]:
github.com/buildkite/terraform-provider-buildkite/buildkite.(*clusterDefaultQueueResource).Read(0xc00121e030, {0xe66a80?, 0xc0017b0390}, {{{{0xe6b278, 0xc0017d3b00}, {0xc0cf60, 0xc0017d3a10}}, {0xe6cb30, 0xc0015ad400}}, 0xc00041c078, ...}, ...)
github.com/buildkite/terraform-provider-buildkite/buildkite/resource_cluster_default_queue.go:160 +0x389
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001938c0, {0xe66a80, 0xc0017b0390}, 0xc0017b0420, 0xc000749630)
github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_readresource.go:101 +0x677
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001938c0, {0xe66a80?, 0xc0017b0240?}, 0xc0015cf940)
github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_readresource.go:55 +0x41a
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0001e2b40, {0xe66a80?, 0xc0014f9c80?}, 0xc000bdd680)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xcfc900?, 0xc0001e2b40}, {0xe66a80, 0xc0014f9c80}, 0xc00020c3f0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002061e0, {0xe6b618, 0xc000386340}, 0xc001589560, 0xc000364990, 0x13dcd10, 0x0)
google.golang.org/grpc@v1.58.3/server.go:1374 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc0002061e0, {0xe6b618, 0xc000386340}, 0xc001589560, 0x0)
google.golang.org/grpc@v1.58.3/server.go:1751 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.58.3/server.go:986 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.58.3/server.go:997 +0x15c

Error: The terraform-provider-buildkite_v1.1.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

(edit: Initially I ran into the problem while trying another change, but further debugging looks like the problem was entirely with the way the default cluster queue object got defined.)

**To Reproduce**

The best way I know to reproduce the problem is to add a a primary cluster default object that has the same id for the cluster_id as for the object id itself. I don't know how to do this. To fix the crash, remove the object from the terraform state (e.g. `terraform state rm buildkite_cluster_default_queue.<name>`). 

edit: I was also able to reproduce the crash by importing a default cluster queue resource. The import succeeded, and then I got a stack trace that was very similar to the one above. As far as I know, there wasn't anything special about the default cluster queue.

**Expected behavior**

I expect it to generate a plan without crashing.

**Additional context**

n/a

**Comment by rayalan** [comment] 2023-12-05 15:10
One additional note: 

```
terraform state show buildkite_cluster_default_queue.<name>
```
results in an object with the cluster id and the id being the same, which seems a little suspicious:

```
resource "buildkite_cluster_default_queue" "<name>" {
    cluster_id = "<id1>=="
    id         = "<id1>=="
    queue_id   = "<id2>"
    uuid       = "<uuid>"
}
```

**Comment by james2791** [comment] 2023-12-05 22:39
Hey @rayalan!

Thanks for letting us know of this - and the note of reproduction: we'll assess what might be the cause

**Comment by jradtilbrook** [comment] 2023-12-11 05:04
Hi @rayalan this looks be an issue when creating a cluster from the API (including terraform) since it doesn't create the default queue at the same time. So what's happened here is that the cluster exists but there is no default queue (and the code doesn't check if its null either!).

We'll get that fixed up in and released in an upcoming patch

**Closed** 2023-12-14 01:28 UTC
Labels: bug
