### ISSUE TITLE
Can no longer create pipelines after upgrading to `1.x` from `0.27.0`

### ISSUE THREAD

**Issue by daxxog** [buildkite/terraform-provider-buildkite#445] opened 2023-12-01 17:19 UTC
**Describe the bug**
After following the [steps to upgrade to v1.0](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/guides/upgrade-v1) I am no longer able to create new pipelines for my GitHub repositories using the terraform provider.

The error I get:
```
buildkite_pipeline.this: Creating...
╷
│ Error: Failed to create pipeline
│
│   with buildkite_pipeline.this,
│   on main.tf line 35, in resource "buildkite_pipeline" "this":
│   35: resource "buildkite_pipeline" "this" {
│
│ Failed to create pipeline: input: Please ensure at least one team is added to this pipeline
│
╵
```

**To Reproduce**
Original terraform, working in `0.27.0`:
```hcl
locals {
  organization = "my-org"
  repo = "my-repo"
  buildkite_team = "my-team"
  team_access = "MANAGE_BUILD_AND_READ"
}

terraform {
  required_providers {
    buildkite = {
      source = "buildkite/buildkite"
      version = "0.27.0"
    }
    github = {
      source = "integrations/github"
    }
  }
}

provider "buildkite" {
  organization = local.organization
}

provider "github" {
  owner = local.organization
}

data "github_repository" "this" {
  full_name = "${local.organization}/${local.repo}"
}

resource "buildkite_pipeline" "this" {
  name           = local.repo
  repository     = data.github_repository.this.ssh_clone_url
  default_branch = data.github_repository.this.default_branch
  steps          = <<EOF
agents:
  queue: "something"

steps:
  - command: "blah.sh"
  - command: "blahblah.sh"
  - label: "Yada"
    command: "yada.sh"
    agents:
      queue: "other"
EOF

  provider_settings {
    publish_commit_status                         = true
    publish_commit_status_per_step                = true
    separate_pull_request_statuses                = true
    build_branches                                = true
    build_tags                                    = true
    build_pull_requests                           = true
    build_pull_request_forks                      = false
    skip_pull_request_builds_for_existing_commits = false
    trigger_mode                                  = "code"
  }

  team {
    slug         = local.buildkite_team
    access_level = local.team_access
  }
}

resource "github_repository_webhook" "this" {
  repository = data.github_repository.this.name

  configuration {
    url          = resource.buildkite_pipeline.this.webhook_url
    content_type = "json"
    insecure_ssl = false
  }

  active = true

  /* According to Buildkite docs:
   *
   * Check Let me select individual events. and the following events:

      - Deployments

      - Pull Requests

      - Pushes
  */
  events = ["deployment", "pull_request", "push"]
}

```

New terraform, broken in `1.x` (I tested on `1.1.1` when writing this issue):
```hcl
locals {
  organization = "my-org"
  repo = "my-repo"
  buildkite_team = "my-team"
  team_access = "MANAGE_BUILD_AND_READ"
}

terraform {
  required_providers {
    buildkite = {
      source = "buildkite/buildkite"
    }
    github = {
      source = "integrations/github"
    }
  }
}

provider "buildkite" {
  organization = local.organization
}

provider "github" {
  owner = local.organization
}

data "github_repository" "this" {
  full_name = "${local.organization}/${local.repo}"
}

data "buildkite_team" "team" {
  slug = local.buildkite_team
}

resource "buildkite_pipeline" "this" {
  name           = local.repo
  repository     = data.github_repository.this.ssh_clone_url
  default_branch = data.github_repository.this.default_branch
  steps          = <<EOF
agents:
  queue: "something"

steps:
  - command: "blah.sh"
  - command: "blahblah.sh"
  - label: "Yada"
    command: "yada.sh"
    agents:
      queue: "other"
EOF

  provider_settings = {
    publish_commit_status                         = true
    publish_commit_status_per_step                = true
    separate_pull_request_statuses                = true
    build_branches                                = true
    build_tags                                    = true
    build_pull_requests                           = true
    build_pull_request_forks                      = false
    skip_pull_request_builds_for_existing_commits = false
    trigger_mode                                  = "code"
  }
}

resource "buildkite_pipeline_team" "pipeline_team" {
  pipeline_id  = resource.buildkite_pipeline.this.id
  team_id      = data.buildkite_team.team.id
  access_level = local.team_access
}

resource "github_repository_webhook" "this" {
  repository = data.github_repository.this.name

  configuration {
    url          = resource.buildkite_pipeline.this.webhook_url
    content_type = "json"
    insecure_ssl = false
  }

  active = true

  /* According to Buildkite docs:
   *
   * Check Let me select individual events. and the following events:

      - Deployments

      - Pull Requests

      - Pushes
  */
  events = ["deployment", "pull_request", "push"]
}

```

Difference between old and new terraform:
```diff
12d11
<       version = "0.27.0"
31a31,34
> data "buildkite_team" "team" {
>   slug = local.buildkite_team
> }
> 
49c52
<   provider_settings {
---
>   provider_settings = {
59a63
> }
61,64c65,68
<   team {
<     slug         = local.buildkite_team
<     access_level = local.team_access
<   }
---
> resource "buildkite_pipeline_team" "pipeline_team" {
>   pipeline_id  = resource.buildkite_pipeline.this.id
>   team_id      = data.buildkite_team.team.id
>   access_level = local.team_access

```

**Expected behavior**
New pipelines are able to be created using the Buildkite terraform provider.

**Additional context**
I think this is related to https://github.com/buildkite/terraform-provider-buildkite/issues/84, where I also [commented](https://github.com/buildkite/terraform-provider-buildkite/issues/84#issuecomment-1784993440).

**Comment by james2791** [comment] 2023-12-05 21:40
Hey @daxxog!

If you have access to a state backup - that would be the most ideal way. The only callout of course being that `v0.27.0` is the specific version where that `team` block removal -> `buildkite_pipeline_team` translation for all team membership in your pipeline resources needs to occur, which is what I believe is blocking you here.

There will be that small window where the translation to the `buildkite_pipeline_team` occurs (teams removed then added again), but after that, you should be able to move over to `v1.1.1`+ and create new pipelines again without issues. 

Let us know how you go 👍

**Comment by daxxog** [comment] 2023-12-05 21:53
Yes, to confirm, the two terraform snippets I shared and the results I am encountering (`v1.1.1`-->`Please ensure at least one team is added to this pipeline`) are both tested against fresh terraform states.

**Comment by james2791** [comment] 2023-12-05 23:43
Thanks @daxxog 

Given you said that this is _also_ happening on fresh state: I'll have a more closer look and attempt to replicate. The only other indicator being is that is the API token that you are using to invoke the plans/applies an Administrator of the organization? That error message is a directive from that from the API, though from the provider's side, the `vXX` -> `v0.27.0` -> `v1.0`+ would need that intermediary switch for the team membership as we chatted on above

**Comment by james2791** [comment] 2023-12-07 04:52
No worries - that looks like the full-suite of REST scopes, and GraphQL being permissive too. 

Shall do some investigating - we'll relay if any more information is needed

**Comment by daxxog** [comment] 2023-12-07 09:19
Thank you @james2791 !

**Comment by lucasoskorep** [comment] 2023-12-11 17:20
@james2791 I am running into the same issue on my end as well.  I am not a BK org admin and the pipeline cannot be created. 

I have the same scopes as above, testing the same way, and also just finished migrating to 0.27.0 to 1.1.0 and having this issue.

**Comment by james2791** [comment] 2023-12-11 22:37
Hey @lucasoskorep - thanks for letting me know a similar case has occurred - on the premise as above, was there a point on `v0.27.0` where you transitioned from the `team` block over to the new `buildkite_pipeline_team ` resource and _then_ moving over to `v1.0.0`+? 

My working assessment as of writing is the jump over without the initial transition (also through tests on my side) but would be also good to know how that team <-> pipeline relationship was handled too to nail the case down!

**Comment by lucasoskorep** [comment] 2023-12-11 22:45
Hey @james2791 

So I reformatted the state from scratch at 0.27.0. I created the new pipeline_team resources in addition to our pipelines and then imported all of them into the state using the provided instructions and terraform import. 

From there I bumped the version to 1.0.0+ , changed the equals sign on provider_settings in the pipeline_team, planned,  and applied. 

After this everything works with existing pipelines but I cannot create any new pipelines.

**Comment by james2791** [comment] 2023-12-15 05:50
Thanks for the loop @lucasoskorep! (also applies to you @daxxog)

Seems like this one might be a little more tricky to reproduce as all attempts on my side are proving fruitful with the `team` block -> `buildkite_pipeline_team` resource through a `v0.26.0` -> `0.27.0` -> `v1.x` upgrade process. Will close this one out for now, but would like to look at each of your cases closer specifically to reproduce/see a common trend and then take action on what can be done with resolving the creation errors. Could you both please [send](https://buildkite.com/support) through org links/names of tokens etc and any/all resource configuration (outside additionally shared as above)?

Much obliged and thanks for the patience so far 🙂

**Comment by james2791** [comment] 2024-01-08 04:13
Full loop also to you @lucasoskorep - Happy New Year also!

We've worked out that this is a quirky side-effect of using an API token tied to a User (non Administrator BK account as discussed above) and the ruling around what these users can do (as that small, intermediate window where a pipeline is moved from the `team` block over to the `buildkite_pipeline_team` is something an Administrative token can only do . We'll be looking into this in the near future but will liaise on any potential updates that we have (also with any releases that directly target this).

Thanks for your patience too!

**Comment by mcncl** [comment] 2024-03-04 02:01
Fixed in https://github.com/buildkite/terraform-provider-buildkite/pull/479 I believe.

**Closed by mcncl** 2024-03-04 02:01 UTC
Labels: bug
