### ISSUE TITLE
Error adding simple pipeline. Asks for team when team is already specified.

### ISSUE THREAD

**Issue by apanzerj** [buildkite/terraform-provider-buildkite#84] opened 2020-12-19 00:22 UTC
```
terraform {
  required_providers {
    buildkite = {
      source  = "buildkite/buildkite"
      version = "0.0.17"
    }
  }
}

resource "buildkite_pipeline" "test" {
  name       = "Panzer Test 1"
  repository = "github.com:pagerduty/web"

  steps = file("steps.yml")

  team {
    slug         = "sustainability"
    access_level = "MANAGE_BUILD_AND_READ"
  }
}

provider "buildkite" {
  # Configuration options
  api_token    = "redacted" # can also be set from env: BUILDKITE_API_TOKEN
  organization = "pagerduty"                                # can also be set from env: BUILDKITE_ORGANIZATION
}
```

Output:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # buildkite_pipeline.test will be created
  + resource "buildkite_pipeline" "test" {
      + cancel_intermediate_builds = false
      + id                         = (known after apply)
      + name                       = "Panzer Test 1"
      + repository                 = "github.com:pagerduty/web"
      + skip_intermediate_builds   = false
      + slug                       = (known after apply)
      + steps                      = <<~EOT

            steps:
              - label: ':pipeline:'
                command: buildkite-agent upload
        EOT
      + team                       = [
          + {
              + access_level = "MANAGE_BUILD_AND_READ"
              + slug         = "sustainability"
            },
        ]
      + webhook_url                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

buildkite_pipeline.test: Creating...

Error: Please ensure at least one team is added to this pipeline

  on main2.tf line 16, in resource "buildkite_pipeline" "test":
  16: resource "buildkite_pipeline" "test" {
```

Note: My token has full access to all the things but is not administrator in the org. I can validate that I have... enough... permissions cause I can make the same pipeline manually in the UI. I'm a team member of the Sustainability team and that is the correct slug. 

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/buildkite/buildkite v0.0.17
```

**Comment by yob** [comment] 2020-12-20 10:35
I've dug into this a bit and have some notes, but no solid plan yet.

The provider creates a pipeline using the `PipelineCreate` graphql mutation. It leaves the configured teams off the request, and only creates the pipeline/team association(s) after the pipeline create succeeds.

However in Buildkite orgs that use teams, only org admins can create a pipeline without a team.

The  `PipelineCreate` graphql mutation does support teams being included, so I suspect the fix is to do everything in the single mutation. I'm not sure if that will have other consequences though. At the very least we'll need to convert the team slug into a graphql id before calling the mutation :thinking:  

/cc @jradtilbrook - it'd be interesting to get your perspective. Maybe the pipeline and team creation is done in two stages for a good reason.

**Comment by yob** [comment] 2020-12-20 12:48
Oh look, I found some relevant history: #31, #48, #43.

I've confirmed in the graphql explorer that the following mutation can create a pipeline and assign it to team(s) in one go:

```graphql
mutation pipelineCreate {
  pipelineCreate(
    input: {
      defaultBranch: "master"
      description: "testing"
      name: "testing"
      organizationId: "abc123"
      repository: {
        url: "https://github.com/buildkite/terraform-provider-buildkite.git"
      }
      steps: { yaml: "" },
      teams:[
        {id:"qqqaaa", accessLevel: BUILD_AND_READ }
      ]
    }
  ) {
    organization {
      id
    }
    pipeline {
      id
      name
    }
  }
}
``` 

My golang foo isn't good enough to work out how to conditionally add the `teams` property to the query in this part of the code:

https://github.com/buildkite/terraform-provider-buildkite/blob/42b66042fb347879ddd4985c14ec9a70e9f63c59/buildkite/resource_pipeline.go#L156-L172

The `github.com/shurcooL/graphql` package is a bit of a mystery to me. I might have to come back to this in the new year when I can pair with a colleague to get it over the line.

**Comment by jradtilbrook** [comment] 2020-12-23 01:36
@yob looks like you've found what you needed now. The pipeline resource code predates the addition of teams which was added in those issues you linked

**Comment by nitrocode** [comment] 2021-02-19 15:52
We're hitting this same issue when using a non-admin API token. It works for Admin users and fails for all other users.

Eager to see this fix in the next release. Thanks to OP for writing this ticket and for the recent commits by yob. 😄

**Closed** 2021-03-10 03:31 UTC

**Comment by daxxog** [comment] 2023-10-30 11:30
I am running into this issue after [upgrading](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/guides/upgrade-v1) to `1.0.4` from `0.27.0` on new [buildkite_pipeline_team](https://registry.terraform.io/providers/buildkite/buildkite/1.0.4/docs/resources/pipeline_team) resources. Existing resources in the state are working correctly.

**Comment by jradtilbrook** [comment] 2023-11-01 02:35
Hmm @daxxog could you provide more info and a reproduction in a new issue for what you are seeing? The code related to this is so old and been refactored that a new issue with details makes more sense. We can look into it from there

**Comment by jsoo1** [comment] 2023-11-10 18:56
I'm seeing the same as @daxxog but I think this issue is so old a new one should be created.

**Comment by daxxog** [comment] 2023-11-10 19:06
@jsoo1 Sorry about that, I haven't had time to draft up an issue yet. Hopefully I'll get more time in the next few weeks to do this.

**Comment by jsoo1** [comment] 2023-11-10 22:48
Sorry I just realized that my token lacked organization admin privilege and I just got this error message, confusingly.

I'll open a separate issue.
